### ISSUE TITLE
Refactor app

### ISSUE THREAD

**Issue by TomVeniat** [VincSP/Dash-Vision#18]
The current app makes all the processing happen in the `back.py` module.
I think we should separate business logic from data access, as in classical 3-Tier architectures.
That would require splitting the current back into  `app_logic` and `data` files where the former contains all the data processing and the latter only contains calls to the database (MongoManager for now).

**Comment by TomVeniat** [comment]
As I see it, the first step is to chunk what is currently the `MongoManager` in two parts: 
- A *data* part, in which all calls to the database are made but **nothing else**, the data processing will be done in the second part. For example, current methods `get_experiment_names` and `_get_database_names` already do that.
- A *logic* part, responsible for all processing operations. For instance, handling data to fit the format expeted by the front-end components as done here
https://github.com/VincSP/Dash-Vision/blob/239e3636bb6010e35061ae216696eabedd9eda01/back.py#L60
 or processing operations that doesn't require new data (*e.g.*  `flter_rows_by_query`)

For the implementation we can keep it simple, I suggest to move the `MongoManager` class to a new `data.py` module and create a new `AppLogic` class for the logic part. This logic class has a `data_manager` attribute (which will be  a  `MongoManager` instance) to which it will delegate every data access requests. 
The `index.py` will then only have access to an `AppLogic` instance, without ever knowing about the `MongoManager`. 

I'm probably missing some things but I think it's enough to get a good draft of the new structure.

**Comment by VincSP** [comment]
I let you check on "archi" branch what i did.
No more "back.py"
News : data.py and logic.py
I added underscore to each function in data.py so we can re use the name's function in logic.py
I did try to put most of the "logic" or "data transformation" code in logic.py.
You can run app but first table's data doesn't populate the table.

**Comment by TomVeniat** [comment]
Ok, great job!
We should just make the change also in the tab files (in the `apps` folder) and then you can send a PR!

**Comment by TomVeniat** [comment]
Closed by #19
