### ISSUE TITLE
CHeck why the global state (such as `column` variable) isn't common accross sessions.

### ISSUE THREAD

**Issue by VincSP** [VincSP/Dash-Vision#4]
Doing: Vincent

**Comment by VincSP** [comment]
I read that dash framework run on the top of flask microFramework.
Flask uses thread-local objects internally so that we don’t have to pass objects around from function to function within a request in order to stay threadsafe.
Moreover our variable 'columns' is declare global inside callback function. so we can believe that every time we call this function, a thread is created and our global variable column is aware from modifiction in differents session.

**Comment by TomVeniat** [comment]
The [Sharing data between callbacks](https://dash.plot.ly/sharing-data-between-callbacks) section of the doc explains why our global variables aren't shared across sessions: 

> **Dash is designed to work in multi-user environments where multiple people may view the application at the same time and will have independent sessions.**
> 
> If your app uses modified global variables, then one user's session could set the variable to one value which would affect the next user's session.
> 
> Dash is also designed to be able to run with multiple python workers so that callbacks can be executed in parallel. This is commonly done with gunicorn using syntax like
> 
> `$ gunicorn --workers 4 app:server`
> 
> (app refers to a file named app.py and server refers to a variable in that file named server: server = app.server).
> 
> When Dash apps run across multiple workers, their memory is not shared. This means that if you modify a global variable in one callback, that modification will not be applied to the rest of the workers.
