### ISSUE TITLE
Compare pandas dataframe query method with Dashs Datable filters.

### ISSUE THREAD

**Issue by VincSP** [VincSP/Dash-Vision#5]
Doing: Vincent

**Comment by VincSP** [comment]
https://dash.plot.ly/datatable/filtering 
I invite you to read this documentation on dash filtering.
We have two possibilities as we said previously. The first one is filtering with front end by turn on the function : 
to find int : > or < or = num(int)
to find string : eq "string"

The other possibility offer by dash is to using server side (back) and implement our filtering methods in a callback.

**Comment by emited** [comment]
Shall we test DataFrame queries, which is more flexible (allows comparing values of two columns for example), and uses a common syntax?

**Comment by TomVeniat** [comment]
The Pandas query approach seems indeed to be a better solution for now. Not harder to implement and way more expressive (at the cost of a few network calls but that shouldn't be a problem).

**Comment by TomVeniat** [comment]
Implemented in #7
