### ISSUE TITLE
Add Store components to the application to keep information when navigating between tabs.

### ISSUE THREAD

**Issue by VincSP** [VincSP/Dash-Vision#8]
Only at session level for now.

**Doing:** Vincent

**Comment by VincSP** [comment]
I'm trying to implement Flask_Caching as recommended here :  https://dash.plot.ly/performance
Memoization stores the results of a function after it is called and re-uses the result if the function is called with the same arguments.
I wanted to use this solution to see if we can store data in cache and after re use it if user want to.
But our actual architecture make things a bit more complicated and i'm not able to implement it for the moment...
Any idea ?

**Comment by VincSP** [comment]
I'd implement Flask_Caching, working great. 
Can use @cache.memoize on callbacks

**Comment by TomVeniat** [comment]
Caching will be useful to enhance the performance of our application but I think it should be added as a different feature.
Here I was thinking of the [Dash Store component](https://dash.plot.ly/dash-core-components/store), to keep information about the user session in the client browser, allowing to keep the state of each tab when navigating between them.
